# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: publish

on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      target_release_tag:
        description: The tag of the release you want to append the artifact to
        required: true

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [
          17,    # Current Java LTS & minimum supported by Minecraft
        ]
        # and run on both Linux and Windows
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          distribution: adopt
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: publish to maven
        run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_enjaraiMavenUsername: ${{ secrets.PUBLISH_MAVEN_USERNAME }}
          ORG_GRADLE_PROJECT_enjaraiMavenPassword: ${{ secrets.PUBLISH_MAVEN_PASSWORD }}
      - name: capture build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '17' }} # Only upload artifacts built from latest java on one OS
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/

  # The part that publishes the compiled mod
  publish:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: download build artifacts
        id: download
        uses: actions/download-artifact@v2
        with:
          name: Artifacts
      - name: Read mod version
        id: mod_version
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: gradle.properties
          property: mod_version
      - name: Update GitHub Release
        uses: tubone24/update_release@v1.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body_path: CHANGELOG.md
          is_append_body: true
      - name: publish mod
        uses: Kir-Antipov/mc-publish@v3.2
        with:

          name: ${{ github.event.release.name }}
          version: ${{ steps.mod_version.outputs.value }}
          version-type: release

          game-versions: |
            1.16
            1.16.1
            1.16.2
            1.16.3
            1.16.4
            1.16.5
            
            1.18
            1.18.1
            1.18.2
            
            1.19
            1.19.1
            1.19.2

            1.19.3
            23w03a
            23w04a
            23w05a
            23w06a
            23w07a
            1.19.4-pre1
            1.19.4-pre2
            1.19.4-pre3
            1.19.4-pre4
          java: |
            8
            16
            17
            18
          modrinth-featured: false

          changelog-file: CHANGELOG.md
          files: '${{ steps.download.outputs.download-path }}/!(*-@(dev|sources)).jar'

          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

